#!/bin/bash -l

################################################################################
#Script Name: 
#Description: 
#Args       : None 
#Author     : Georgia Doing
#Email      : georgia.doing@duke.edu
################################################################################

##SBATCH --partition=standard
###SBATCH --partition=bigmem
#SBATCH --job-name=wpc
#SBATCH --time=0-08:00:00
##SBATCH --nodes=1
##SBATCH --ntasks-per-node=16
#SBATCH -cpus-per-task=16
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=georgia.doing@duke.edu
##SBATCH --array=10001-15000%20
#SBATCH -o /work/gd134/oe/%u-%x-%A-%a
#SBATCH --mem=128G
###SBATCH --hostlist=[k01-58]

#
#




cd $SLURM_SUBMIT_DIR

conda activate radage

python weighted_pearson_correlation_parallel_edit_dcc.py /work/gd134/adage_models /work/gd134/wcor_ec_mgp_450.csv 571,670 8 6390

